# Generated by Django 2.0.1 on 2022-05-14 01:50

import diary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(validators=[diary.validators.validate_title_content]),
        ),
        migrations.AlterField(
            model_name='page',
            name='dt_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(error_messages={'unique': '이미 있는 제목'}, max_length=50, unique=True, validators=[diary.validators.validate_title_content]),
        ),
    ]
