# Generated by Django 2.0.1 on 2022-05-20 15:50

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[blog.validators.validate_title_content])),
                ('content', models.TextField()),
                ('dt_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
